# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import llm_harness_pb2 as harness__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in harness_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HarnessStub:
    """gRPC control contract for the harness process.
    Streaming events (text, thinking, tools, compaction, usage) go over SSE
    (:9001/events); here — commands and synchronous replies only.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ask = channel.unary_unary(
                '/harness.v1.Harness/Ask',
                request_serializer=harness__pb2.AskRequest.SerializeToString,
                response_deserializer=harness__pb2.AskReply.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/harness.v1.Harness/Stop',
                request_serializer=harness__pb2.Empty.SerializeToString,
                response_deserializer=harness__pb2.RunStatus.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/harness.v1.Harness/Resume',
                request_serializer=harness__pb2.Empty.SerializeToString,
                response_deserializer=harness__pb2.RunStatus.FromString,
                _registered_method=True)
        self.SetSettings = channel.unary_unary(
                '/harness.v1.Harness/SetSettings',
                request_serializer=harness__pb2.Settings.SerializeToString,
                response_deserializer=harness__pb2.Settings.FromString,
                _registered_method=True)
        self.Compact = channel.unary_unary(
                '/harness.v1.Harness/Compact',
                request_serializer=harness__pb2.CompactRequest.SerializeToString,
                response_deserializer=harness__pb2.CompactReply.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/harness.v1.Harness/Status',
                request_serializer=harness__pb2.Empty.SerializeToString,
                response_deserializer=harness__pb2.StatusReply.FromString,
                _registered_method=True)
        self.GetMessages = channel.unary_unary(
                '/harness.v1.Harness/GetMessages',
                request_serializer=harness__pb2.GetMessagesRequest.SerializeToString,
                response_deserializer=harness__pb2.GetMessagesReply.FromString,
                _registered_method=True)
        self.NewSession = channel.unary_unary(
                '/harness.v1.Harness/NewSession',
                request_serializer=harness__pb2.NewSessionRequest.SerializeToString,
                response_deserializer=harness__pb2.AskReply.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/harness.v1.Harness/ListSessions',
                request_serializer=harness__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=harness__pb2.ListSessionsReply.FromString,
                _registered_method=True)
        self.LoadSession = channel.unary_unary(
                '/harness.v1.Harness/LoadSession',
                request_serializer=harness__pb2.LoadSessionRequest.SerializeToString,
                response_deserializer=harness__pb2.AskReply.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/harness.v1.Harness/DeleteSession',
                request_serializer=harness__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=harness__pb2.DeleteSessionReply.FromString,
                _registered_method=True)
        self.RenameSession = channel.unary_unary(
                '/harness.v1.Harness/RenameSession',
                request_serializer=harness__pb2.RenameSessionRequest.SerializeToString,
                response_deserializer=harness__pb2.RenameSessionReply.FromString,
                _registered_method=True)


class HarnessServicer:
    """gRPC control contract for the harness process.
    Streaming events (text, thinking, tools, compaction, usage) go over SSE
    (:9001/events); here — commands and synchronous replies only.

    """

    def Ask(self, request, context):
        """Accept a user message and start/continue an agent run.
        If a run is already active the message is queued (steering) and executes
        after the current assistant turn. The reply is immediate: run id,
        progress arrives over SSE.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Stop the current run: the LLM stream is torn down, pending tool calls are
        not executed (an already-started bash command runs to its timeout).
        History is preserved; Resume can continue the loop.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Resume a stopped run: continue the loop with the current history.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSettings(self, request, context):
        """Change settings on the fly (fields left at 0/"" are unchanged).
        Takes effect from the next LLM request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Compact(self, request, context):
        """Manual compaction of the history (see CompactRequest).
        Executes between turns (waits for the current turn if a run is active).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Current state: settings, run, token counts, queue depth.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessages(self, request, context):
        """Conversation history (in RAM) for the UI. last=0 returns the full
        history; last>0 returns the trailing N messages. Read-only snapshot;
        live changes still arrive over SSE.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewSession(self, request, context):
        """Discard the conversation and start a fresh session (system prompt only).
        The previous session (if it has messages) is archived first, so it shows
        up in ListSessions. Allowed only when no run is active or paused.
        root: switch the working folder for the new session ("" = keep the
        current one).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """All sessions of the daemon: the currently loaded one plus the archived
        ones (<root>/.llm-harness/sessions/<id>.jsonl). root selects one working
        folder ("" = every folder this daemon has been in, union). Each entry
        carries the folder it belongs to. Sorted by last update, newest first.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadSession(self, request, context):
        """Load an archived session as the current one (its content is copied back
        to the active session file and replayed into RAM). The current session is
        archived first (if it has messages). Allowed only when no run is active
        or paused.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Delete a session. For an archived session the file is removed. For the
        currently loaded one its history is discarded and a fresh session starts
        (same precondition as NewSession).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameSession(self, request, context):
        """Rename a session (active or archived): sets a display name that
        overrides the preview in ListSessions. Empty name clears it.
        Allowed while a run is active.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HarnessServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ask': grpc.unary_unary_rpc_method_handler(
                    servicer.Ask,
                    request_deserializer=harness__pb2.AskRequest.FromString,
                    response_serializer=harness__pb2.AskReply.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=harness__pb2.Empty.FromString,
                    response_serializer=harness__pb2.RunStatus.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=harness__pb2.Empty.FromString,
                    response_serializer=harness__pb2.RunStatus.SerializeToString,
            ),
            'SetSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSettings,
                    request_deserializer=harness__pb2.Settings.FromString,
                    response_serializer=harness__pb2.Settings.SerializeToString,
            ),
            'Compact': grpc.unary_unary_rpc_method_handler(
                    servicer.Compact,
                    request_deserializer=harness__pb2.CompactRequest.FromString,
                    response_serializer=harness__pb2.CompactReply.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=harness__pb2.Empty.FromString,
                    response_serializer=harness__pb2.StatusReply.SerializeToString,
            ),
            'GetMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=harness__pb2.GetMessagesRequest.FromString,
                    response_serializer=harness__pb2.GetMessagesReply.SerializeToString,
            ),
            'NewSession': grpc.unary_unary_rpc_method_handler(
                    servicer.NewSession,
                    request_deserializer=harness__pb2.NewSessionRequest.FromString,
                    response_serializer=harness__pb2.AskReply.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=harness__pb2.ListSessionsRequest.FromString,
                    response_serializer=harness__pb2.ListSessionsReply.SerializeToString,
            ),
            'LoadSession': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadSession,
                    request_deserializer=harness__pb2.LoadSessionRequest.FromString,
                    response_serializer=harness__pb2.AskReply.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=harness__pb2.DeleteSessionRequest.FromString,
                    response_serializer=harness__pb2.DeleteSessionReply.SerializeToString,
            ),
            'RenameSession': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameSession,
                    request_deserializer=harness__pb2.RenameSessionRequest.FromString,
                    response_serializer=harness__pb2.RenameSessionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'harness.v1.Harness', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('harness.v1.Harness', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Harness:
    """gRPC control contract for the harness process.
    Streaming events (text, thinking, tools, compaction, usage) go over SSE
    (:9001/events); here — commands and synchronous replies only.

    """

    @staticmethod
    def Ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harness.v1.Harness/Ask',
            harness__pb2.AskRequest.SerializeToString,
            harness__pb2.AskReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harness.v1.Harness/Stop',
            harness__pb2.Empty.SerializeToString,
            harness__pb2.RunStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harness.v1.Harness/Resume',
            harness__pb2.Empty.SerializeToString,
            harness__pb2.RunStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harness.v1.Harness/SetSettings',
            harness__pb2.Settings.SerializeToString,
            harness__pb2.Settings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Compact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harness.v1.Harness/Compact',
            harness__pb2.CompactRequest.SerializeToString,
            harness__pb2.CompactReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harness.v1.Harness/Status',
            harness__pb2.Empty.SerializeToString,
            harness__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harness.v1.Harness/GetMessages',
            harness__pb2.GetMessagesRequest.SerializeToString,
            harness__pb2.GetMessagesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NewSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harness.v1.Harness/NewSession',
            harness__pb2.NewSessionRequest.SerializeToString,
            harness__pb2.AskReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harness.v1.Harness/ListSessions',
            harness__pb2.ListSessionsRequest.SerializeToString,
            harness__pb2.ListSessionsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harness.v1.Harness/LoadSession',
            harness__pb2.LoadSessionRequest.SerializeToString,
            harness__pb2.AskReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harness.v1.Harness/DeleteSession',
            harness__pb2.DeleteSessionRequest.SerializeToString,
            harness__pb2.DeleteSessionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenameSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harness.v1.Harness/RenameSession',
            harness__pb2.RenameSessionRequest.SerializeToString,
            harness__pb2.RenameSessionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
